version: '3'

services:
  db:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: '${DJANGO_DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DJANGO_DB_NAME}'
      MYSQL_USER: '${DJANGO_DB_USER}'
      MYSQL_PASSWORD: '${DJANGO_DB_PASSWORD}'
    container_name: drf-blog-db
    networks:
      private-drf-nw:
        ipv4_address: 192.168.82.200
    volumes:
      - drfBlogDB:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - "8000:8000"
    container_name: drf-blog-web
    networks:
      private-drf-nw:
        ipv4_address: 192.168.82.100
    depends_on:
      db:
        condition: service_started
    env_file:
      - ./.env
networks:
  private-drf-nw:
    driver: bridge
    name: private-drf-nw
    ipam:
      driver: default
      config:
      - subnet: 192.168.82.0/24
volumes:
  drfBlogDB:
    name: drfBlogDB
